### ISSUE TITLE
Consider increasing complexity of can_process

### ISSUE THREAD

**Issue by schinckel** [funkybob/graaf#6]
I think it might be worthwhile to sniff the first line (or more) of files: then you'd be able to have jekyll and simple markdown files in the same tree: and just have the jekyll ones with the YAML header.

**Comment by funkybob** [comment]
For this specific case, process() can return False to indicate it didn't... and the Processor will continue looking for a processor.

The current Jekyl generator does this if it doesn't find the document separator.
